# Generated by Django 2.2.12 on 2021-10-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211030_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='args',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
